###     Numpy (PART 15)

In [1]:
""" 
(Assignment)
Differnce between list and numpy array
Use list when you need flexibility and mixed data.

Use NumPy array when working with large datasets, numerical computation, or matrices (Hydrology/Hydropower applications would benefit from NumPy arrays).

"""

' \n(Assignment)\nDiffernce between list and numpy array\nUse list when you need flexibility and mixed data.\n\nUse NumPy array when working with large datasets, numerical computation, or matrices (Hydrology/Hydropower applications would benefit from NumPy arrays).\n\n'

In [ ]:
"""
Instructions 

1st install the required library using ( Pip install numpy)
(pip install pandas)

pip show pandas

pip list   #environment vitra j j install chha sabai dekhaai dinchha 
"""


"""
numpy maa numerical computation garna help hunchha 

"""

In [3]:
# Importing required library
import numpy as np

In [5]:
#Creating an array 
array=np.array([1,2,3,4,5,0,9,8])
print(array)
print(array.shape)

[1 2 3 4 5 0 9 8]
(8,)


In [9]:
# Alternative way of importing from numpy module 
#Creating array 
from numpy import array
array=array([1,2,3,4,5])
print(array)
print(array.shape)

[1 2 3 4 5]
(5,)


In [7]:
# creating 2d array 
array_2d=np.array([[1,2,3,4,5],[5,6,7,8,9,]])
print(array_2d)
print(array_2d.shape)

[[1 2 3 4 5]
 [5 6 7 8 9]]
(2, 5)


In [8]:
#Printing the row and column of any numpy array

row,col=array_2d.shape
print(row,col)

2 5


In [10]:
# Element-wise multiplication garna 
array*2

array([ 2,  4,  6,  8, 10])

In [11]:
#Create the new array and sort
array1=np.array([3,9,6,0,2,40])
array1.sort()
array1


array([ 0,  2,  3,  6,  9, 40])

In [13]:
# Square garnu paryo vane 
array1**2

array([   0,    4,    9,   36,   81, 1600])

In [15]:
# Array vitra ko sabai element laai sum,mean garnu paryo vane 
# array.sum()
array.mean()

np.float64(3.0)

In [16]:
#Creating two arrays arr1 and arr2 and sum them 
# Python List
list1 = [1, 2, 3, 4]
list2 = [5, 6, 7, 8]

# Adding lists -> Concatenates
print(list1 + list2)  


# NumPy Array
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([5, 6, 7, 8])

# Adding arrays -> Element-wise addition
print(arr1 + arr2)  




[1, 2, 3, 4, 5, 6, 7, 8]
[ 6  8 10 12]


#### PANDAS

In [19]:
#Importing required library
import pandas as pd   
""" 
Pandas is requird when you have to work in tabular form , dataframe  
"""

' \nPandas is requird when you have to work in tabular form , dataframe  \n'

In [20]:
#create pandas series
series=pd.Series([1,2,3,4,5],index=["a","b","c","d","e"])
print(series)


a    1
b    2
c    3
d    4
e    5
dtype: int64


In [24]:
#create pandas series without index
series=pd.Series([1,2,3,4,5])
# print(series)
# print(series.index)   #( index laai show garxha )
# print(series.values)     #(Given array ko value aaucha )
print(series.shape)       #(Given series ko dimension aaucha)


(5,)


In [26]:
# Creating a pandas Dataframe with column name 
data={'name':['john','Praneez','Om shankar'],
      'age':[29,27,25],
      'city':['New York','Los Angeles','Chicago']}

df=pd.DataFrame(data)
print(df)
print(df.shape)    #( Yesle k garchha given dataframe ko size dinchha)

         name  age         city
0        john   29     New York
1     Praneez   27  Los Angeles
2  Om shankar   25      Chicago
(3, 3)


In [27]:
data

{'name': ['john', 'Praneez', 'Om shankar'],
 'age': [29, 27, 25],
 'city': ['New York', 'Los Angeles', 'Chicago']}